version: "3.9"
services:
  db:
    image: postgres:16.2-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=tmsdb
    volumes:
      - db_data:/var/lib/postgresql/data
    command: >
      sh -c "
        until psql -h localhost -U postgres -d tmsdb -c '\l' &>/dev/null; do
          sleep 1;
        done
        psql -U postgres -d tmsdb -f /docker-entrypoint-initdb.d/create_db.sql
      "
  app:
    build: .Dockerfile
    ports:
      - "8085:8085"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/tmsdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres

volumes:
  db_data: